### ISSUE TITLE
Crash during meeting

### ISSUE THREAD

**Issue by gfodor** [mozilla/janus-plugin-sfu#10]
Had a crash happen during meeting, around :34 minute mark at end of this log. Don't see any errors though.

**Comment by gfodor** [comment]
https://mozilla.slack.com/files/U723XJLDP/FA3P7LEBZ/janus.log.gz

(apologies for slack link, easiest atm)

**Comment by mquander** [comment]
Is there a core dump on the box? That would be most helpful.

**Comment by mquander** [comment]
(Closing since I don't think we have any way to diagnose this.)
