### ISSUE TITLE
Remove squawker CLI and associated code?

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/janus-plugin-sfu#20]
Automated squawker bots will be superseded by https://github.com/mozilla/hubs/pull/370, so we can probably remove the related code from this repo. Specifically:
- https://github.com/mozilla/janus-plugin-sfu/blob/master/client/squawkers-cli.js
- https://github.com/mozilla/janus-plugin-sfu/blob/master/client/squawkers.js#L148-L160
- and maybe all of https://github.com/mozilla/janus-plugin-sfu/blob/master/client/squawkers.js#L142-L195

**Comment by mquander** [comment]
Yeah, I agree. I will clean this stuff up.
