### ISSUE TITLE
Please update README: Janus package in Debian supports data channels now

### ISSUE THREAD

**Issue by jonassmedegaard** [mozilla/janus-plugin-sfu#31]
Hi, Debian package maintained of Janus here.

I notice that you explicitly warn against using distro-packaged Janus due to of lack of data Channels support.  It is correct that until recently Janus in Debian (and by extension derivatives like Ubuntu) did not link against libusrsctp and therefore lacked support for data channels.

Recently, however, libusrsctp got updated and since Janus releases since 0.6.0-2 released 2019-02-07 link against libusrctp and should therefore support data channels.

Please doublecheck, and consider updating README of this project.

**Comment by mqp** [comment]
Thanks for letting me know, that's great. I will test it out using the stock Janus on my Ubuntu and recommend that in the README if everything seems to work well.
