### ISSUE TITLE
Config erroneously implies that setting 0 for max_room_size and max_ccu means no limit

### ISSUE THREAD

**Issue by jbaicoianu** [mozilla/janus-plugin-sfu#56]
I tried setting max_ccu in `janus.plugin.sfu.jcfg` to 0 and was unable to connect to the server, which was returning a "Server is full" error.  Expected behavior is that this would disable the limit, instead it seems a limit of 0 is enforced.

**Comment by mqp** [comment]
Good catch, I will fix this up.

**Comment by vincentfretin** [comment]
@mqp we should at least just remove the "Zero means no limit." in `janus.plugin.sfu.cfg.sample` or change the code to not make any check if equals 0.
See also https://github.com/mozilla/janus-plugin-sfu/issues/57
