### ISSUE TITLE
max_ccu setting is misleading

### ISSUE THREAD

**Issue by jbaicoianu** [mozilla/janus-plugin-sfu#57]
From the naming and the comments in the config, `max_ccu` seems to imply that it's a user limit, when in reality it appears to be a session limit.  Since number of sessions scale as `(number of users)^2`, the default limit of 1000 actually supports a much smaller number of users than expected.

**Comment by vincentfretin** [comment]
Yes, the `(number of users)^2` is a nice info to have in the comment. We should change
`# If present, the maximum number of concurrent users allowed to join any room on the server.`
by
`# If present, the maximum number of concurrent sessions the server can support. The number of sessions in a room is (number of users)^2`
