### ISSUE TITLE
Remove again lazy_static dependency?

### ISSUE THREAD

**Issue by vincentfretin** [mozilla/janus-plugin-sfu#64]
@mqp I just saw an old PR https://github.com/mozilla/janus-plugin-sfu/pull/41 where you removed the usage of lazy_static.
The multi threading PR reintroduced the dependency
https://github.com/mozilla/janus-plugin-sfu/pull/49
Can we remove again the dependency and use OneCell or something like that?
I'm not familiar with those Rust constructs so I'm not sure how to change it.

**Comment by mqp** [comment]
Good suggestion, fixed it up.

**Comment by vincentfretin** [comment]
Thank you!
