### ISSUE TITLE
Write some documentation about auth_key and the JWT content

### ISSUE THREAD

**Issue by vincentfretin** [mozilla/janus-plugin-sfu#77]
See my comment here
https://github.com/mozilla/dialog/issues/8#issuecomment-683903134
We need to have some documentation in this repository. I'll probably do a PR here once I get to implement it in my app.

**Comment by vincentfretin** [comment]
FYI I updated the example in my naf-janus-adapter repo branch 3.0.x to generate a client id and set it with setClientId https://github.com/Synantoo/naf-janus-adapter/blob/3.0.x/examples/index.html
You just need to change the url to your hosted janus and the example now works.
We didn't have any working example before in the naf-janus-adapter, this was unfortunate.

**Comment by vincentfretin** [comment]
Quick notes while I implemented it in my app. I may remove the comment later and revisit this doing a PR
Generate a private/public key:

    ssh-keygen -t rsa -b 2048 -f key.pem -N ''
    openssl rsa -in key.pem -outform PEM -pubout -out public.pem
    openssl rsa -in key.pem -outform DER -out key.der
    openssl rsa -in key.der -inform DER -RSAPublicKey_out -outform DER -out public.der

Janus side in `janus.plugin.sfu.cfg`, specify `auth_key` to the public key in DER format

    auth_key = /path/to/public.der

Backend side, simple Phoenix backend with phx_gen_auth and a room table associated to the user table.
Add guardian dependency to `mix.exs`:

    {:guardian, "~> 2.0"},

Execute:

    mix deps.get

This will add those new dependencies:

    guardian 2.1.1
    jose 1.11.1

create `lib/myapp_web/perms_token.ex`
```
defmodule MyAppWeb.PermsToken do
  @moduledoc """
  generate token for creator of the room "123":
  MyAppWeb.PermsToken.token_for_perms(%{user_id: 1, kick_users: true, join_hub: true, room_ids: ["123"]})
  generate token for another authenticated participant for room "123":
  MyAppWeb.PermsToken.token_for_perms(%{user_id: 2, kick_users: false, join_hub: true, room_ids: ["123"]}})
  generate token for anonymous:
  MyAppWeb.PermsToken.token_for_perms(%{kick_users: false, join_hub: true, room_ids: ["123"]}})

  """
  use Guardian, otp_app: :myapp, secret_fetcher: MyAppWeb.PermsTokenSecretFetcher, allowed_algos: ["RS512"]

  def subject_for_token(_resource, %{"user_id" => user_id}) do
    {:ok, to_string(user_id)}
  end

  def subject_for_token(_resource, _claims) do
    {:ok, "anon"}
  end

  # we don't use the inverse
  def resource_from_claims(_), do: nil

  def token_for_perms(perms) do
    {:ok, token, _claims} =
      MyAppWeb.PermsToken.encode_and_sign(
        # PermsTokens do not have a resource associated with them
        nil,
        perms |> Map.put(:aud, :webrtc_auth),
        ttl: {5, :minutes},
        allowed_drift: 60 * 1000
      )
    token
  end
end

defmodule MyAppWeb.PermsTokenSecretFetcher do
  def fetch_signing_secret(mod, _opts) do
    {:ok, Application.get_env(:myapp, mod)[:perms_key] |> JOSE.JWK.from_pem_file()}
  end

  def fetch_verifying_secret(mod, _token_headers, _opts) do
    {:ok, Application.get_env(:myapp, mod)[:perms_key] |> JOSE.JWK.from_pem_file()}
  end
end
```

Start the backend with the environment variable pointing to the private key in PEM format:

    AUTH_KEY_PRIVATE=/path/to/key.pem mix phx.server

in `config/config.exs` (for development)

    config :myapp, MyAppWeb.PermsToken, perms_key: System.get_env("AUTH_KEY_PRIVATE")

in `config/releases.exs` or `config/runtime.exs` (for production):

    config :meetingrooms, MeetingroomsWeb.PermsToken, perms_key: System.get_env("AUTH_KEY_PRIVATE") ||
    raise """
    environment variable AUTH_KEY_PRIVATE is missing.
    """

Do your security logic and generate a token like this for example:

    MeetingroomsWeb.PermsToken.token_for_perms(
      %{user_id: user.id, kick_users: user.id == room.user_id, join_hub: true, room_ids: [room.slug]})

and send it via rest/graphql/socket to the browser. 
On the frontend side, in the adapter-ready listener:

    const permsToken = await callSomeAPItoGetTheToken();
    adapter.setJoinToken(permsToken);

**Comment by vincentfretin** [comment]
On the frontend side, there is more to do that just the initial `setJoinToken`! :D
The JWT is valid here 5 minutes. If participant A joins the room and participant B joins the room 5 minutes later, B will hear A, but A won't hear B because A couldn't subscribe to B's audio because of an expired token (`addOccupant/createSubscriber` called after receiving a `join` event in naf-janus-adapter). You will get in janus logs 
```
[WARN] Rejecting join from 0x7fb91400fc50 to room my-room as user 3196610745608672. Error: ExpiredSignature
```

You need to renew the JWT regularly, like every 4 minutes, you can hard code the 4 minutes in the code below (`const nextRefresh = 4 * 60 * 1000;`) or check the `exp` in the JWT with [jwt-decode](https://www.npmjs.com/package/jwt-decode) and subtract a margin like 1 min (in case you change the ttl of the JWT in your backend later) . Here is an example:
```
import jwt_decode from "jwt-decode";

const refreshPermsToken = async () => {
  const permsToken = await callSomeAPItoGetTheToken();
  NAF.connection.adapter.setJoinToken(permsToken);
  delayedRefreshPermsToken(permsToken);
}

const delayedRefreshPermsToken = (permsToken) => {
  // This doesn't validate the token
  const decoded = jwt_decode(permsToken);
  // Refresh the token 1 minute before it expires.
  const nextRefresh = new Date(decoded.exp * 1000 - 60 * 1000) - new Date();
  setTimeout(async () => {
    if (!NAF.connection.adapter) {
      // we disconnected
      return;
    }
    await refreshPermsToken();
  }, nextRefresh);
}
document.addEventListener('DOMContentLoaded', () => {
  const scene = document.querySelector('a-scene');
  scene.addEventListener('adapter-ready', ({ detail: adapter }) => {
    const clientId = getYourClientId();
    adapter.setClientId(clientId);
    const permsToken = await callSomeAPItoGetTheToken();
    adapter.setJoinToken(permsToken);
    delayedRefreshPermsToken(permsToken);
    // do your thing with getUserMedia and adapter.setLocalMediaStream
  });
});

```

**Comment by PlumCantaloupe** [comment]
Thank you for this note. I was wondering why I couldn't get this adapter to work; but I guess you need audio on for the rest of the data to work ( I was trying to do this without streaming audio).

**Comment by vincentfretin** [comment]
If you didn't see it, read the janus deployment doc I wrote https://github.com/networked-aframe/naf-janus-adapter/pull/8
We can discuss on A-Frame slack if you have some issues setting it up.

**Comment by PlumCantaloupe** [comment]
Ah nice, didn't see that. Very helpful thank you.

**Comment by vincentfretin** [comment]
I removed the content of my two comments. I moved the content and rewrote some paragraphs in the documentation there https://github.com/networked-aframe/naf-janus-adapter/blob/master/docs/securing-janus-with-jwt.md
